/* Atlas Tamghrabit - Data Module (with Unsplash queries) */
'use strict';

const AtlasData = {
    // ── Cities ──────────────────────────────────────────────────────
    cities: [
        {
            id: 'marrakech',
            name: 'Marrakech',
            nameAr: 'مراكش',
            subtitle: 'La Ville Ocre',
            subtitleAr: 'المدينة الحمراء',
            color: '#E2725B',
            colorRgb: '226, 114, 91',
            unsplashQuery: 'Marrakech rooftop medina Morocco',
            intro: `Fondée au XIe siècle par les Almoravides, Marrakech est le cœur battant du Maroc. La médina, inscrite au patrimoine mondial de l'UNESCO, abrite des palaces, des jardins mystiques et des souks labyrinthiques.`,
            coords: { lat: 31.6295, lng: -7.9811 },
            coordsDisplay: '31.6295° N, 7.9811° O',
            heroAlt: 'Place Jemaa el-Fna de nuit',
            population: '1 070 838',
            founded: '1070',
            region: 'Marrakech-Safi',
            highlights: ['Jemaa el-Fna', 'Jardins de la Menara', 'Musée Yves Saint Laurent'],
            videoId: '6aL_iAiBuXQ',
            videoTitle: "L'Histoire de Marrakech — La Ville Ocre",
        },
        {
            id: 'fes',
            name: 'Fès',
            nameAr: 'فاس',
            subtitle: 'La Capitale Spirituelle',
            subtitleAr: 'عاصمة الروح',
            color: '#006B3E',
            colorRgb: '0, 107, 62',
            unsplashQuery: 'Fes tannery medina Morocco',
            intro: `Fondée en 789 par Idris Ier, Fès est la plus ancienne capitale impériale du Maroc. Sa médina de Fès el-Bali, la plus grande médina médiévale du monde, abrite l'université Al Quaraouiyine, fondée en 859.`,
            coords: { lat: 34.0181, lng: -5.0078 },
            coordsDisplay: '34.0181° N, 5.0078° O',
            heroAlt: 'Les tanneries Chouara de Fès',
            population: '1 150 131',
            founded: '789',
            region: 'Fès-Meknès',
            highlights: ['Al Quaraouiyine', 'Bab Boujeloud', 'Tanneries Chouara'],
            videoId: 'vpcrtTdLp5Q',
            videoTitle: "Fès el-Bali — La Plus Ancienne Université du Monde",
        },
        {
            id: 'chefchaouen',
            name: 'Chefchaouen',
            nameAr: 'شفشاون',
            subtitle: 'La Perle Bleue',
            subtitleAr: 'اللؤلؤة الزرقاء',
            color: '#00B4D8',
            colorRgb: '0, 180, 216',
            unsplashQuery: 'Chefchaouen blue streets Morocco',
            intro: `Nichée dans les montagnes du Rif, Chefchaouen éblouit par ses ruelles teintées d'indigo et d'outremer. Fondée en 1471, cette cité andalouse exhale un parfum unique d'authenticité et de sérénité.`,
            coords: { lat: 35.1686, lng: -5.2694 },
            coordsDisplay: '35.1686° N, 5.2694° O',
            heroAlt: 'Ruelles bleues de Chefchaouen',
            population: '45 925',
            founded: '1471',
            region: 'Tanger-Tétouan-Al Hoceïma',
            highlights: ['Kasbah Uta el-Hammam', 'Ras el-Maa', 'Quartier Andalou'],
            videoId: 'aGOaEUj4Ix0',
            videoTitle: "Chefchaouen — Le Secret de la Ville Bleue",
        },
        {
            id: 'essaouira',
            name: 'Essaouira',
            nameAr: 'الصويرة',
            subtitle: 'La Cité des Vents',
            subtitleAr: 'مدينة الرياح',
            color: '#005F73',
            colorRgb: '0, 95, 115',
            unsplashQuery: 'Essaouira ramparts ocean Morocco',
            intro: `Ancrée sur l'Atlantique, Essaouira est une cité fortifiée d'une grâce unique. Ses remparts portugais, ses petites galeries d'art et ses luthiers de bois de thuya font de cette ville un joyau culturel hors du commun.`,
            coords: { lat: 31.5085, lng: -9.7595 },
            coordsDisplay: '31.5085° N, 9.7595° O',
            heroAlt: 'Les remparts d\'Essaouira face à l\'Atlantique',
            population: '77 966',
            founded: '1765',
            region: 'Marrakech-Safi',
            highlights: ['Remparts & Sqala', 'Place Moulay Hassan', 'Mellah Juif'],
            videoId: 'rT5lnm31lwE',
            videoTitle: "Essaouira — L'Âme de l'Atlantique Marocain",
        },
        {
            id: 'meknes',
            name: 'Meknès',
            nameAr: 'مكناس',
            subtitle: 'La Ville Ismaïlienne',
            subtitleAr: 'المدينة الإسماعيلية',
            color: '#8B4513',
            colorRgb: '139, 69, 19',
            unsplashQuery: 'Meknes medina Morocco imperial',
            intro: `Meknès, quatrième ville impériale du Maroc, fut bâtie par le Sultan Moulay Ismaïl au XVIIe siècle. Surnommée 'le Versailles du Maroc', elle impressionne par ses remparts cyclopéens, ses greniers royaux et ses écuries monumentales. Inscrite au patrimoine mondial de l'UNESCO en 1996, elle reste la ville impériale la moins touristique et la plus authentique du Maroc.`,
            coords: { lat: 33.8935, lng: -5.5473 },
            coordsDisplay: '33.8935° N, 5.5473° O',
            heroAlt: 'Bab Mansour de Meknès',
            population: '835 695',
            founded: 'XIe siècle',
            region: 'Fès-Meknès',
            highlights: ['Bab Mansour', 'Heri es-Souani', 'Habs Qara'],
            localImages: ['/assets/cities/meknes/hero.jpg'], // the ui will handle carousel if length > 0
            heroPosition: 'center 40%',
            videoId: 'JZDJxC_UcCE',
            videoTitle: 'Meknès — La Ville Ismaïlienne',
        },
        {
            id: 'tanger',
            name: 'Tanger',
            nameAr: 'طنجة',
            subtitle: 'La Ville du Détroit',
            subtitleAr: 'مدينة البوغاز',
            color: '#1E90FF',
            colorRgb: '30, 144, 255',
            unsplashQuery: 'Tangier Morocco Mediterranean blue white city coast',
            intro: `Tanger, ville mythique au carrefour de l'Afrique et de l'Europe, est la porte d'entrée du Maroc sur le Détroit de Gibraltar. Ancienne zone internationale, elle incarne une Tamghrabit cosmopolite, vibrante et éternellement ouverte sur l'horizon marin.`,
            coords: { lat: 35.7595, lng: -5.8340 },
            coordsDisplay: '35.7595° N, 5.8340° O',
            heroAlt: 'Vue sur la baie de Tanger',
            population: '1 065 601',
            founded: 'Ve siècle av. J.-C.',
            region: 'Tanger-Tétouan-Al Hoceïma',
            highlights: ['La Kasbah', 'Cap Spartel', 'Grottes d\'Hercule'],
            localImages: [],
            videoId: 'GZ-eE_7gRMI',
            videoTitle: 'Tanger — Un peu d\'histoire, d\'hier et d\'aujourd\'hui',
        },
    ],

    // ── Monuments ───────────────────────────────────────────────────
    monuments: [
        // MARRAKECH
        {
            id: 'koutoubia',
            cityId: 'marrakech',
            name: 'Mosquée Koutoubia',
            nameAr: 'جامع الكتبية',
            type: 'Mosquée',
            typeIcon: '🕌',
            year: 1158,
            yearDisplay: 'XIIe siècle',
            height: '70m',
            coords: { lat: 31.6238, lng: -7.9935 },
            unsplashQuery: 'Koutoubia minaret Marrakech',
            description: `La Koutoubia est le symbole architectural de Marrakech. Son minaret de 70 mètres, chef-d'œuvre de l'art almohade, a servi de modèle à la Giralda de Séville et à la Tour Hassan de Rabat. Entouré de jardins embaumés de roses et d'orangers, ce monument de brique marque du sceau de l'éternité la silhouette de la ville ocre.`,
            imageQueries: [
                'Koutoubia minaret Marrakech',
                'Koutoubia mosque minaret sunset Morocco',
                'Marrakech medina mosque tower',
            ],
            nearby: [
                { name: 'Jardin de l\'Agdal', type: 'Jardin historique', dist: '1.2 km', icon: '🌿', imgQuery: 'Moroccan garden historic Marrakech' },
                { name: 'Jemaa el-Fna', type: 'Place emblématique', dist: '450 m', icon: '🎭', imgQuery: 'Jemaa el Fna square Marrakech' },
                { name: 'Musée de Marrakech', type: 'Musée', dist: '900 m', icon: '🎨', imgQuery: 'museum riad Marrakech historic' },
            ],
        },
        {
            id: 'bahia',
            cityId: 'marrakech',
            name: 'Palais de la Bahia',
            nameAr: 'قصر الباهية',
            type: 'Palais',
            typeIcon: '🏛️',
            year: 1894,
            yearDisplay: 'XIXe siècle',
            coords: { lat: 31.6214, lng: -7.9826 },
            unsplashQuery: 'Bahia palace riad Marrakech',
            description: `Le Palais Bahia, dont le nom signifie «brillance», est l'un des exemples les plus aboutis de l'architecture marocaine de la fin du XIXe siècle. Ses 8 hectares de patios, jardins parfumés et salles décorées de zelliges et de bois de cèdre sculpté témoignent du raffinement extrême d'une époque dorée.`,
            imageQueries: [
                'Bahia palace riad Marrakech',
                'Moroccan palace courtyard ornate zellige',
                'Marrakech palace architecture interior',
            ],
            nearby: [
                { name: 'Palais El Badi', type: 'Palais en ruines', dist: '800 m', icon: '🏚️', imgQuery: 'El Badi palace ruins Marrakech Morocco' },
                { name: 'Mellah de Marrakech', type: 'Quartier historique', dist: '200 m', icon: '✡️', imgQuery: 'Marrakech mellah Jewish quarter street' },
                { name: 'Maison Tiskiwin', type: 'Musée ethnographique', dist: '300 m', icon: '🎭', imgQuery: 'Moroccan ethnographic museum artifacts' },
            ],
        },
        {
            id: 'el-badi',
            cityId: 'marrakech',
            name: 'Palais El Badi',
            nameAr: 'قصر البديع',
            type: 'Palais',
            typeIcon: '🏛️',
            year: 1578,
            yearDisplay: 'XVIe siècle',
            coords: { lat: 31.6196, lng: -7.9829 },
            unsplashQuery: 'El Badi palace ruins storks Marrakech',
            description: `Surnommé «L'Incomparable», El Badi fut édifié par Ahmed el-Mansour après la victoire de la Bataille des Trois Rois. Ses 360 pièces ornées de marbre de Carrare, d'onyx et d'or, dont les ruines subsistent encore, évoquent une splendeur passée. Aujourd'hui, les cigognes et les palmiers règnent souverainement sur ses vestiges.`,
            imageQueries: [
                'El Badi palace ruins storks Marrakech',
                'Marrakech ancient palace ruins Morocco',
                'Moroccan saadian palace historic ruins',
            ],
            nearby: [
                { name: 'Saâdiennes Tombs', type: 'Mausolée', dist: '500 m', icon: '⚱️', imgQuery: 'Saadian tombs Marrakech mausoleum' },
                { name: 'Bab Agnaou', type: 'Porte almoravide', dist: '600 m', icon: '🚪', imgQuery: 'Bab Agnaou gate Marrakech historic' },
                { name: 'Mosque Ben Youssef', type: 'Mosquée', dist: '1.1 km', icon: '🕌', imgQuery: 'Ben Youssef mosque Marrakech minaret' },
            ],
        },
        // FÈS
        {
            id: 'bab-boujeloud',
            cityId: 'fes',
            name: 'Bab Boujeloud',
            nameAr: 'باب بو جلود',
            type: 'Porte historique',
            typeIcon: '🚪',
            localImage: '/assets/monuments/bab_boujloud.jpg',
            year: 1913,
            yearDisplay: 'Début XXe siècle',
            coords: { lat: 34.0617, lng: -4.9767 },
            unsplashQuery: 'Bab Boujeloud blue gate Fes',
            description: `Bab Bou Jeloud, surnommée la «Grande Porte», est l'entrée principale de la médina de Fès el-Bali. Construite en 1913 sous le protectorat français, elle affiche une façade extérieure turquoise en zelliges et une façade intérieure verte — la couleur sacrée d'Islam. Ornementée d'arabesques dorées, elle est le joyau de la médina fassi.`,
            imageQueries: [
                'Bab Boujeloud blue gate Fes',
                'Fes blue gate medina entrance Morocco',
                'Fes el Bali gate zellige tiles',
            ],
            nearby: [
                { name: 'Médersa Bou Inania', type: 'École coranique', dist: '200 m', icon: '📖', imgQuery: 'Bou Inania madrasa Fes Morocco' },
                { name: 'Souk el-Attarine', type: 'Souk des épices', dist: '800 m', icon: '🌿', imgQuery: 'souk spices Morocco medina' },
                { name: 'Fontaine Nejjarine', type: 'Fontaine', dist: '400 m', icon: '💧', imgQuery: 'Nejjarine fountain Fes Morocco historic' },
            ],
        },
        {
            id: 'chouara',
            cityId: 'fes',
            name: 'Tanneries Chouara',
            nameAr: 'دباغة الشوارة',
            type: 'Artisanat traditionnel',
            typeIcon: '🎨',
            localImage: '/assets/monuments/chouara.png',
            year: 1100,
            yearDisplay: 'XIe siècle',
            coords: { lat: 34.0636, lng: -4.9715 },
            unsplashQuery: 'Fes tannery Chouara color vats Morocco',
            description: `Les tanneries Chouara figurent parmi les plus vieilles au monde. Fondées au XIe siècle, elles utilisent des méthodes inchangées depuis des millénaires. Les cuves de teinture en granit, du blanc de la chaux au rouge de la garance, composent une palette chromatique qui a fasciné Delacroix et inspira de nombreux artistes.`,
            imageQueries: [
                'Fes tannery Chouara color vats Morocco',
                'tannery leather dyeing pits Morocco',
                'Chouara tannery aerial view Fes',
            ],
            nearby: [
                { name: 'Quartier des Andalous', type: 'Quartier historique', dist: '600 m', icon: '🏘️', imgQuery: 'Andalusian quarter Fes Morocco alley' },
                { name: 'Fondouk Tetouani', type: 'Fondouk historique', dist: '300 m', icon: '🏛️', imgQuery: 'caravanserai fonduk Fes Morocco historic' },
                { name: 'Mosquée des Andalous', type: 'Mosquée', dist: '500 m', icon: '🕌', imgQuery: 'Andalousian mosque Fes medina' },
            ],
        },
        {
            id: 'al-attarine',
            cityId: 'fes',
            name: 'Médersa Al-Attarine',
            nameAr: 'مدرسة العطارين',
            type: 'École coranique',
            typeIcon: '📖',
            localImage: '/assets/monuments/al_attarine.jpg',
            year: 1325,
            yearDisplay: 'XIVe siècle',
            coords: { lat: 34.0640, lng: -4.9735 },
            unsplashQuery: 'Al Quaraouiyine mosque Fes',
            description: `Édifiée par le sultan mérinide Abou Saïd Othman II vers 1325, la médersa Al-Attarine est considérée comme l'un des plus beaux exemples de l'architecture mérinide. Son patio central est entièrement orné de zelliges polychromes, de stuc finement travaillé et de bois de cèdre sculpté, illustrant le génie artisanal fassi.`,
            imageQueries: [
                'Al Quaraouiyine mosque Fes',
                'Al-Attarine madrasa Fes zellige stucco',
                'Moroccan madrasa courtyard cedar carving',
            ],
            nearby: [
                { name: 'Al Quaraouiyine', type: 'Université-mosquée', dist: '50 m', icon: '🕌', imgQuery: 'Al Qarawiyyin university mosque Fes' },
                { name: 'Dar Batha (Musée)', type: 'Musée', dist: '1.2 km', icon: '🎨', imgQuery: 'Dar Batha museum Fes Morocco palace' },
                { name: 'Mosquée Rcif', type: 'Mosquée', dist: '400 m', icon: '🕌', imgQuery: 'Morocco mosque medina old city minaret' },
            ],
        },
        // CHEFCHAOUEN
        {
            id: 'kasbah-chefchaouen',
            cityId: 'chefchaouen',
            name: 'Kasbah Uta el-Hammam',
            nameAr: 'قصبة عطا الحمام',
            type: 'Kasbah',
            typeIcon: '🏰',
            year: 1471,
            yearDisplay: 'XVe siècle',
            coords: { lat: 35.1685, lng: -5.2687 },
            localImage: '/assets/monuments/kasbah_1.jpg',
            localImages: [
                '/assets/monuments/kasbah_1.jpg',
                '/assets/monuments/kasbah_2.jpg',
                '/assets/monuments/kasbah_3.jpg'
            ],
            unsplashQuery: 'Kasbah Chefchaouen Morocco',
            description: `La kasbah d'Uta el-Hammam, édifiée en 1471 par Ali ibn Rashid al-Alami, est le cœur historique de Chefchaouen. Ses tours octogonales et ses jardins andalous, baignés par les eaux de source de Ras el-Maa, accueillent aujourd'hui un musée retraçant l'histoire de la ville et une galerie d'art ethnographique.`,
            imageQueries: [
                'Kasbah Chefchaouen Morocco',
                'Chefchaouen fortress walls blue city',
                'Chefchaouen kasbah garden Morocco',
            ],
            nearby: [
                { name: 'Place Uta el-Hammam', type: 'Place centrale', dist: '50 m', icon: '☕', localImg: '/assets/monuments/place_uta_hammam.png', imgQuery: 'Chefchaouen main square blue Morocco' },
                { name: 'Mosquée de la grande place', type: 'Mosquée', dist: '80 m', icon: '🕌', localImg: '/assets/monuments/grande_mosquee.jpg', imgQuery: 'Chefchaouen mosque octagonal minaret Morocco' },
                { name: 'Quartier Andalou', type: 'Quartier historique', dist: '200 m', icon: '🏘️', imgQuery: 'Chefchaouen blue alley stairs Morocco' },
            ],
        },
        {
            id: 'ras-el-maa',
            cityId: 'chefchaouen',
            name: 'Cascade de Ras el-Maa',
            nameAr: 'عين راس الماء',
            type: 'Site naturel',
            typeIcon: '💧',
            year: 1471,
            yearDisplay: 'Fondation XVe siècle',
            coords: { lat: 35.1700, lng: -5.2663 },
            localImage: '/assets/monuments/ras_el_maa_1.jpg',
            localImages: [
                '/assets/monuments/ras_el_maa_1.jpg',
                '/assets/monuments/ras_el_maa_2.jpg',
                '/assets/monuments/ras_el_maa_3.jpg'
            ],
            unsplashQuery: 'Ras el Maa waterfall Chefchaouen Morocco',
            description: `Ras el-Maa, la source principale de Chefchaouen, est un lieu sacré où l'eau pure des montagnes du Rif s'écoule en cascade dans un bassin séculaire. C'est ici que les femmes de la ville viennent laver le linge depuis des générations, perpétuant un rituel social immuable au cœur de la médina bleue.`,
            imageQueries: [
                'Ras el Maa waterfall Chefchaouen Morocco',
                'mountain stream Rif Morocco nature',
                'Chefchaouen water source Morocco',
            ],
            nearby: [
                { name: 'Pont de Dieu', type: 'Site naturel', dist: '45 min', icon: '⛰️', localImg: '/assets/monuments/pont_de_dieu.jpg', imgQuery: 'Gods Bridge Akchour Morocco landscape' },
                { name: 'Mosquée Espagnole', type: 'Point de vue', dist: '1.5 km', icon: '🕌', localImg: '/assets/monuments/jardins_kasbah.jpg', imgQuery: 'Spanish Mosque Chefchaouen Morocco' },
                { name: 'Jardins de la Kasbah', type: 'Jardin historique', dist: '600 m', icon: '🌳', localImg: '/assets/monuments/mosquee_espagnole.jpg', imgQuery: 'Chefchaouen kasbah gardens nature' },
            ],
        },
        {
            id: 'grande-mosquee-chefchaouen',
            cityId: 'chefchaouen',
            name: 'Grande Mosquée',
            nameAr: 'المسجد الأعظم',
            type: 'Mosquée',
            typeIcon: '🕌',
            year: 1471,
            yearDisplay: 'XVe siècle',
            coords: { lat: 35.1684, lng: -5.2688 },
            localImage: '/assets/monuments/grande_mosquee.jpg',
            unsplashQuery: 'Chefchaouen mosque minaret octagonal Morocco',
            description: `La Grande Mosquée de Chefchaouen, fondée par Ali ibn Rashid, se distingue par son minaret octogonal andalou, unique au Maroc. Les arabesques finement sculptées de ses murs, sa cour intérieure inondée de lumière et ses colonnes de marbre blanc en font l'un des monuments les plus raffinés du nord du Maroc.`,
            imageQueries: [
                'Chefchaouen mosque minaret octagonal Morocco',
                'Chefchaouen blue medina mosque',
                'Rif Morocco mosque architecture',
            ],
            nearby: [
                { name: 'Kasbah Uta el-Hammam', type: 'Forteresse', dist: '80 m', icon: '🏰', imgQuery: 'Kasbah Chefchaouen fortress Morocco' },
                { name: 'Fontaine de la Place', type: 'Fontaine', dist: '60 m', icon: '⛲', imgQuery: 'Chefchaouen blue fountain square Morocco' },
                { name: 'Pharmacie du peuple', type: 'Commerce historique', dist: '150 m', icon: '🌿', imgQuery: 'Moroccan herbs spices traditional shop' },
            ],
        },
        // ESSAOUIRA
        {
            id: 'remparts-essaouira',
            cityId: 'essaouira',
            name: 'Remparts & Sqala',
            nameAr: 'أسوار الصويرة',
            type: 'Remparts',
            typeIcon: '🏰',
            year: 1765,
            yearDisplay: 'XVIIIe siècle',
            coords: { lat: 31.5094, lng: -9.7710 },
            unsplashQuery: 'Essaouira Skala fort ramparts',
            description: `Les remparts d'Essaouira, dessinés par l'architecte Théodore Cornut sur ordre du sultan Sidi Mohammed ben Abdallah, sont parmi les mieux préservés d'Afrique du Nord. La Sqala du port, avec ses canons du XVIIIe siècle pointés vers l'Atlantique, offre un panorama grandiose sur les vagues déchaînées et l'archipel des Purpuraires.`,
            imageQueries: [
                'Essaouira Skala fort ramparts',
                'Essaouira cannons ramparts Atlantic ocean',
                'Essaouira fortress walls Morocco coast',
            ],
            nearby: [
                { name: 'Port d\'Essaouira', type: 'Port historique', dist: '300 m', icon: '⛵', imgQuery: 'Essaouira fishing port boats Morocco' },
                { name: 'Place Moulay Hassan', type: 'Place centrale', dist: '500 m', icon: '☕', imgQuery: 'Essaouira Moulay Hassan square Morocco' },
                { name: 'Galerie Damgaard', type: 'Galerie d\'art', dist: '400 m', icon: '🎨', imgQuery: 'Essaouira art gallery moroccan painter' },
            ],
        },
        {
            id: 'sqala-port',
            cityId: 'essaouira',
            name: 'Sqala du Port',
            nameAr: 'سقالة الميناء',
            type: 'Forteresse',
            typeIcon: '🏰',
            year: 1765,
            yearDisplay: 'XVIIIe siècle',
            coords: { lat: 31.5057, lng: -9.7734 },
            localImage: '/assets/monuments/sqala_1.png',
            localImages: [
                '/assets/monuments/sqala_1.png',
                '/assets/monuments/sqala_2.jpg',
                '/assets/monuments/sqala_3.png'
            ],
            unsplashQuery: 'Essaouira port fortification cannon Atlantic',
            description: `La Sqala du port est une plateforme d'artillerie monumentale dominant l'Atlantique. Ses tours de garde, ses canons de bronze hollandais et ses créneaux en pierre dorée sont l'essence d'Essaouira — ce mélange d'histoire portugaise, hollandaise et marocaine qui fait la singularité de cette cité cosmopolite.`,
            imageQueries: [
                'Essaouira port fortification cannon Atlantic',
                'Essaouira rampart tower seagulls Atlantic',
                'Essaouira Morocco coast fortification',
            ],
            nearby: [
                { name: 'Remparts Nord', type: 'Remparts', dist: '400 m', icon: '🏰', imgQuery: 'Essaouira north ramparts fortifications' },
                { name: 'Archipel Purpuraires', type: 'Site naturel', dist: '2 km en mer', icon: '🏝️', imgQuery: 'Essaouira islands Purpuraires Atlantic Morocco' },
                { name: 'Medina d\'Essaouira', type: 'Médina', dist: '200 m', icon: '🏘️', imgQuery: 'Essaouira medina white blue walls Morocco' },
            ],
        },
        {
            id: 'mellah-essaouira',
            cityId: 'essaouira',
            name: 'Mellah & Synagogue Slat',
            nameAr: 'ملاح الصويرة',
            type: 'Quartier historique',
            typeIcon: '✡️',
            year: 1807,
            yearDisplay: 'XIXe siècle',
            coords: { lat: 31.5113, lng: -9.7661 },
            unsplashQuery: 'Essaouira medina white blue walls Morocco',
            description: `Le Mellah d'Essaouira, l'un des derniers mellahs subsistants du Maroc, témoigne de la riche histoire judéo-marocaine de la cité. La synagogue Slat Lkhal, restaurée, y accueille encore des pèlerinages annuels. Les ruelles aux façades bleues et blanches conservent la mémoire d'une communauté qui contribua au rayonnement commercial d'Essaouira au XIXe siècle.`,
            imageQueries: [
                'Essaouira medina white blue walls Morocco',
                'Jewish quarter Morocco medina alley',
                'Essaouira old city architecture heritage',
            ],
            nearby: [
                { name: 'Musée Sidi Mohammed ben Abdallah', type: 'Musée', dist: '600 m', icon: '🎨', imgQuery: 'Essaouira museum riad traditional Morocco' },
                { name: 'Atelier thuya', type: 'Artisan', dist: '200 m', icon: '🪵', imgQuery: 'Thuya wood workshop artisan Essaouira' },
                { name: 'Fontaine Chleuh', type: 'Fontaine', dist: '100 m', icon: '💧', imgQuery: 'traditional Moroccan fountain medina' },
            ],
        },
        // MEKNÈS
        {
            id: 'bab-mansour',
            cityId: 'meknes',
            name: 'Bab Mansour',
            nameAr: 'باب منصور لعلج',
            type: 'Porte monumentale',
            typeIcon: '🚪',
            year: 1732,
            yearDisplay: 'XVIIIe siècle',
            coords: { lat: 33.8935, lng: -5.5549 },
            localImage: '/assets/monuments/bab_mansour_new_1.jpg',
            localImages: [
                '/assets/monuments/bab_mansour_new_1.jpg',
                '/assets/monuments/bab_mansour_new_2.jpg',
                '/assets/monuments/bab_mansour_new_3.jpg',
            ],
            unsplashQuery: 'Meknes Bab Mansour gate Morocco',
            description: `Considérée comme la plus belle porte du Maroc et l'une des plus imposantes d'Afrique du Nord. Érigée sous Moulay Ismaïl et achevée par son fils, elle mesure 16m de hauteur. Son nom vient de l'architecte chrétien converti El Mansour qui la conçut. Ornée de zellige polychrome et d'inscriptions coraniques en zellij blanc sur fond vert.`,
            imageQueries: [
                'Meknes Bab Mansour gate Morocco',
                'Morocco imperial city architecture Meknes',
                'Zellige tile Bab Mansour Meknes',
            ],
            nearby: [
                { name: 'Place El Hedim', type: 'Place centrale', dist: '50 m', icon: '☕', localImg: '/assets/monuments/el_hedim.jpg', imgQuery: 'El Hedim square Meknes Morocco' },
                { name: 'Musée Dar Jamaï', type: 'Musée', dist: '120 m', icon: '🏛️', localImg: '/assets/monuments/dar_jamai.jpg', imgQuery: 'Dar Jamai museum Meknes architecture' },
                { name: 'Médina de Meknès', type: 'Médina', dist: '200 m', icon: '🏘️', imgQuery: 'Meknes medina alleys Morocco' },
            ],
        },
        {
            id: 'habs-qara',
            cityId: 'meknes',
            name: 'Habs Qara',
            nameAr: 'حبس قارا',
            type: 'Prison souterraine',
            typeIcon: '🗝️',
            year: 1700,
            yearDisplay: 'XVIIIe siècle',
            coords: { lat: 33.8906, lng: -5.5532 },
            localImage: '/assets/monuments/habs_qara_1.jpg',
            localImages: [
                '/assets/monuments/habs_qara_1.jpg',
                '/assets/monuments/habs_qara_2.jpg',
                '/assets/monuments/habs_qara_3.jpg',
            ],
            unsplashQuery: 'Meknes underground prison Morocco',
            description: `Situé à l'intérieur de la Qasba Ismailienne, ce monument historique date du début du XVIIIème siècle. Il est réputé comme étant un vaste souterrain sombre construit comme un labyrinthe. Connu sous le nom de Habs Qara, ce nom vient du patronyme d’un prisonnier portugais qui reçut du Sultan Alaouite Moulay Ismaïl la promesse d’être libéré s’il parvenait à bâtir une prison de plus de 40.000 détenus. Cette prison est formée par trois salles composées d'une série d'arcades reposant sur des piliers d'une dimension moyenne de 1,40m sur 3,46m et soutenant des voûtes en berceau surbaissées. Après le règne du sultan, elle fut utilisée à titre provisoire comme silos et comme magasins alimentaires.`,
            imageQueries: [
                'Meknes Habs Qara underground',
                'Morocco imperial prison Moulay Ismail',
                'Meknes underground arches',
            ],
            nearby: [
                { name: 'Koubat Al Khayatine', type: 'Monument', dist: '50 m', icon: '🏛️', localImg: '/assets/monuments/koubat_al_khayatine.jpg', imgQuery: 'Koubat Al Khayatine Meknes' },
                { name: 'Place El Hedim', type: 'Place centrale', dist: '350 m', icon: '☕', localImg: '/assets/monuments/el_hedim.jpg', imgQuery: 'El Hedim square Meknes Morocco' },
                { name: 'Mausolée Moulay Ismaïl', type: 'Mausolée', dist: '250 m', icon: '⚱️', localImg: '/assets/monuments/mausolee_moulay_ismail.jpg', imgQuery: 'Moulay Ismail mausoleum Meknes' },
            ],
        },
        {
            id: 'sahrij-souani',
            cityId: 'meknes',
            name: 'Sahrij Souani & Heri es-Souani',
            nameAr: 'صهريج السواني',
            type: 'Édifice impérial',
            typeIcon: '💧',
            year: 1703,
            yearDisplay: 'XVIIIe siècle',
            coords: { lat: 33.8820, lng: -5.5431 },
            localImage: '/assets/monuments/sahrij_souani_1.jpg',
            localImages: [
                '/assets/monuments/sahrij_souani_1.jpg',
                '/assets/monuments/sahrij_souani_2.jpg',
                '/assets/monuments/sahrij_souani_3.jpg',
            ],
            unsplashQuery: 'Sahrij Souani basin Meknes Morocco',
            description: `Le Sahrij Souani est un bassin royal de 4 hectares construit par Moulay Ismaïl pour irriguer ses jardins et alimenter en eau les écuries royales adjacentes. Les Heri es-Souani — greniers et écuries monumentales — pouvaient accueillir 12 000 chevaux de guerre. Leurs voûtes en berceau de 12m de hauteur et leur système de ventilation naturelle témoignent du génie architectural ismaïlien.`,
            imageQueries: [
                'Sahrij Souani basin Meknes Morocco',
                'Heri Souani granary Meknes underground',
                'Meknes imperial stables Moulay Ismail',
            ],
            nearby: [
                { name: 'Jardins de l\'Agdal', type: 'Jardin royal', dist: '100 m', icon: '🌳', imgQuery: 'Morocco Agdal gardens nature' },
                { name: 'Haras Royal', type: 'Écuries', dist: '300 m', icon: '🐎', localImg: '/assets/monuments/haras_royal.jpg', imgQuery: 'Meknes royal stables horses' },
                { name: 'Mausolée Moulay Ismaïl', type: 'Mausolée', dist: '800 m', icon: '⚱️', localImg: '/assets/monuments/mausolee_moulay_ismail.jpg', imgQuery: 'Moulay Ismail mausoleum Meknes mosaic' },
            ],
        },
        // TANGER
        {
            id: 'kasbah_dar_makhzen',
            cityId: 'tanger',
            name: 'La Kasbah & Dar el Makhzen',
            nameAr: 'القصبة ودار المخزن',
            type: 'Palais & Musée',
            typeIcon: '🏰',
            year: 1684,
            yearDisplay: 'XVIIe siècle',
            coords: { lat: 35.7891, lng: -5.8123 },
            localImage: '/assets/monuments/kasbah_dar_makhzen_1.jpg',
            localImages: [
                '/assets/monuments/kasbah_dar_makhzen_1.jpg',
                '/assets/monuments/kasbah_dar_makhzen_2.jpg',
                '/assets/monuments/kasbah_dar_makhzen_3.jpg',
            ],
            unsplashQuery: 'Tangier Kasbah museum palace Morocco',
            description: `Situé au point le plus haut de la ville, ce palais construit sous Moulay Ismaïl témoigne de la puissance historique marocaine. Empreint d'architecture arabo-andalouse, il abrite aujourd'hui le musée de la Kasbah, offrant une vue imprenable sur le détroit de Gibraltar et l'Espagne au loin.`,
            imageQueries: [
                'Tangier Kasbah architecture Morocco',
                'Dar el Makhzen Tangier museum',
                'Tangier medina viewpoint sea',
            ],
            nearby: [
                { name: 'Place de la Kasbah', type: 'Place', dist: '50m', icon: '📍', localImg: '/assets/monuments/place_kasbah.jpg', imgQuery: 'Tangier Kasbah square' },
                { name: 'Café Détroit', type: 'Café historique', dist: '200m', icon: '☕', localImg: '/assets/monuments/cafe_detroit.jpg', imgQuery: 'Cafe Detroit Tangier' },
            ],
        },
        {
            id: 'cap_spartel',
            cityId: 'tanger',
            name: 'Cap Spartel',
            nameAr: 'رأس سبارطيل',
            type: 'Phare maritime',
            typeIcon: '🗼',
            year: 1864,
            yearDisplay: 'XIXe siècle',
            coords: { lat: 35.7903, lng: -5.9231 },
            localImage: '/assets/monuments/cap_spartel_1.jpg',
            localImages: [
                '/assets/monuments/cap_spartel_1.jpg',
                '/assets/monuments/cap_spartel_2.jpg',
                '/assets/monuments/cap_spartel_3.jpg',
            ],
            unsplashQuery: 'Cap Spartel lighthouse Morocco coast',
            description: `Lieu magique où les eaux de l'Atlantique rencontrent celles de la Méditerranée. Son phare iconique est un symbole de sécurité pour les marins depuis plus de 150 ans, dressant fièrement sa lanterne perchée à l'horizon azur et turquoise.`,
            imageQueries: [
                'Cap Spartel lighthouse Morocco',
                'Tangier coast Cap Spartel',
                'Morocco Mediterranean Atlantic meeting point',
            ],
            nearby: [
                { name: 'Grottes d\'Hercule', type: 'Site naturel', dist: '4km', icon: '🌊', imgQuery: 'Hercules caves Tangier sea' },
                { name: 'Forêt de Perdicaris', type: 'Parc', dist: '3km', icon: '🌲', localImg: '/assets/monuments/foret_perdicaris.jpg', imgQuery: 'Morocco Tangier Rmilat forest' },
            ],
        },
        {
            id: 'grottes_hercule',
            cityId: 'tanger',
            name: 'Grottes d\'Hercule',
            nameAr: 'مغارة هرقل',
            type: 'Site naturel',
            typeIcon: '⛰️',
            year: -2000,
            yearDisplay: 'Antiquité',
            coords: { lat: 35.7602, lng: -5.9397 },
            localImage: '/assets/monuments/grottes_hercule_2.jpg',
            localImages: [
                '/assets/monuments/grottes_hercule_2.jpg',
                '/assets/monuments/grottes_hercule_1.png',
                '/assets/monuments/grottes_hercule_3.jpg',
            ],
            unsplashQuery: 'Hercules Caves Tangier Morocco sea view',
            description: `Lieu de légende dont l'ouverture sur la mer dessine la carte inversée de l'Afrique. Un site géologique et mythologique majeur où le héros Hercule serait venu se reposer après avoir accompli ses douze travaux. Les formations rocheuses sont baignées par les vagues puissantes de l'océan Atlantique.`,
            imageQueries: [
                'Hercules Caves Tangier Morocco sea',
                'Caves of Hercules Africa map shape',
                'Tangier Morocco coast caves',
            ],
            nearby: [
                { name: 'Phare de Cap Spartel', type: 'Phare', dist: '4km', icon: '🗼', imgQuery: 'Cap Spartel lighthouse Morocco' },
            ],
        },
    ],

    // ── Artisanat / Heritage per city ───────────────────────────────
    artisanat: {
        marrakech: [
            {
                id: 'tapis',
                name: 'Tapis & Tissage',
                sub: 'Art ancestral berbère',
                unsplashQuery: 'Moroccan carpet souk handmade wool',
                description: `Les tapis berbères de Marrakech sont des œuvres d'art à part entière. Tissés à la main par des artisanes souvent analphabètes, ils codifient en symboles géométriques les croyances, rêves et récits de vie de leurs créatrices. Chaque nœud est un mot, chaque motif une phrase d'une langue textile millénaire.`,
            },
            {
                id: 'zellige',
                name: 'Zellige & Céramique',
                sub: 'Mosaïque de terre cuite',
                unsplashQuery: 'Zellige tilework Morocco ceramic blue',
                description: `Le zellige est l'art de la mosaïque en céramique émaillée, taillée à la main en petites pièces géométriques — des fourmis — puis assemblées en compositions d'une précision mathématique. Introduit par les Almoravides, il orne aujourd'hui palais, mosquées et fontaines, transformant l'architecture en poème de couleurs.`,
            },
            {
                id: 'khettara',
                name: 'Khettaras',
                sub: 'Irrigation souterraine',
                localImage: '/assets/artisanat/khettara.png',
                unsplashQuery: 'Moroccan irrigation system underground khettara oasis',
                description: `Les khettaras sont des galeries drainantes souterraines datant de plus de mille ans, creusées pour acheminer l'eau des nappes phréatiques vers les palmeraies et jardins de Marrakech. Ce génie hydraulique ancestral, inscrit au patrimoine immatériel, irrigue encore aujourd'hui plusieurs quartiers de l'ancienne médina.`,
            },
            {
                id: 'leather',
                name: 'Maroquinerie',
                sub: 'Cuir tanné à la main',
                unsplashQuery: 'Moroccan leather goods handcrafted souk',
                description: `La maroquinerie de Marrakech est reconnue dans le monde entier pour la qualité de son cuir naturel tanné à la végétale — sumac, noix de galle, écorce de grenadier. Les maroquiniers du souk des teinturiers confectionnent babouches, sacs, ceintures et reliures selon des techniques transmises de maître en apprenti depuis des siècles.`,
            },
        ],
        fes: [
            {
                id: 'cuivre',
                name: 'Cuivre & Laiton',
                sub: 'Ciselure et repoussé',
                localImage: '/assets/artisanat/cuivre_fes.jpg',
                unsplashQuery: 'Moroccan copper brass crafts hammered Fes souk',
                description: `La dinanderie fassi est l'un des arts métallurgiques les plus sophistiqués du Maroc. Les naqqacha — ciseleurs — martelent et cisèlent lanterns, théières, miroirs et plateaux avec une précision de joaillier. Le quartier Saffarine, dont le symbole est l'enclume, résonne depuis des siècles du martèlement rythmé des artisans.`,
            },
            {
                id: 'broderie',
                name: 'Broderie Fassi',
                sub: 'Soie & fils d\'or',
                localImage: '/assets/artisanat/broderie_fes.jpg',
                unsplashQuery: 'Fez embroidery Moroccan silk thread handmade',
                description: `La broderie de Fès, dite «point de Fès», se distingue par sa réversibilité parfaite : identique des deux côtés du tissu. Réalisée en soie sur lin ou coton blanc, elle orne nappes, rideaux et tenues de cérémonies. Ses motifs géométriques codifiés répondent à une grammaire formelle héritée de l'Andalousie médiévale.`,
            },
            {
                id: 'poterie',
                name: 'Poterie Bleue',
                sub: 'Faïence de Fès',
                localImage: '/assets/artisanat/poterie_fes.jpg',
                unsplashQuery: 'Fes blue pottery ceramic Morocco traditional',
                description: `La céramique bleue de Fès est célèbre dans le monde entier. Peinte à la main avec de l'oxyde de cobalt sur un fond blanc ivoire, elle représente des arabesque florales, des entrelacs géométriques et des calligraphies. Cuite dans les fours à bois du quartier Ain Nokbi, chaque pièce porte la signature inimitable de son peintre.`,
            },
            {
                id: 'marqueterie-fes',
                name: 'Marqueterie',
                sub: 'Cèdre et ébène',
                localImage: '/assets/artisanat/marqueterie_fes.jpg',
                unsplashQuery: 'Moroccan cedar wood marquetry inlay craft',
                description: `La marqueterie fassi est un art du bois d'une délicatesse exquise. Les menuisiers de la médina incèrent dans le cèdre de l'Atlas des pièces d'ébène, de grenadier, de thuya et d'os pour créer des tableaux géométriques d'une précision mathématique. Plafonds de zaouïas, portes de medersas et moucharabiehs témoignent de cet art de l'ombre et de la lumière.`,
            },
        ],
        chefchaouen: [
            {
                id: 'laine',
                name: 'Tissage de Laine',
                sub: 'Djellabas & burnous',
                unsplashQuery: 'Moroccan weaving textile blue Chefchaouen wool',
                description: `Le tissage de laine des femmes du Rif est une tradition vieille de plusieurs millénaires. La djellaba bleue de Chefchaouen, tissée sur des métiers verticaux en bois de cèdre, est ornée de broderies géométriques en laine teintée à l'indigo. Transmis de mère en fille, ce savoir-faire constitue l'identité culturelle profonde de la montagne rifaine.`,
            },
            {
                id: 'indigo',
                name: 'Teinture Indigo',
                sub: 'La teinte bleue sacrée',
                unsplashQuery: 'indigo natural dye Morocco blue textile',
                description: `L'indigo utilisé à Chefchaouen provient traditionnellement de la plante Indigofera tinctoria, cultivée dans les régions du Rif. Cette teinture naturelle, fixée par un bain de chaux, donne aux tissus cette teinte profonde et persistante. Depuis le XIXe siècle, la ville elle-même s'est parée de blanc et de bleu, en hommage à cette couleur spirituelle et protectrice.`,
            },
            {
                id: 'vannerie',
                name: 'Vannerie & Osier',
                sub: 'Paniers jbila',
                unsplashQuery: 'Moroccan wicker basket weaving handmade',
                description: `La vannerie des montagnes du Rif utilise osier sauvage, jonc et palmier nain pour créer paniers, nattes et corbeilles aux formes ancestrales. Les artisanes jbilas tressent ces objets fonctionnels selon des techniques transmises oralement, incorporant parfois laine colorée et cuir pour ajouter des motifs décoratifs uniques à chaque pièce.`,
            },
        ],
        essaouira: [
            {
                id: 'thuya',
                name: 'Bois de Thuya',
                sub: 'Marqueterie millénaire',
                localImage: '/assets/artisanat/marqueterie_essaouira.jpg',
                unsplashQuery: 'Thuya wood marquetry Essaouira Morocco',
                description: `Le thuya (Tetraclinis articulata) est un arbre endémique du Maghreb dont la loupe — un renflement de la racine — présente un veinage unique aux reflets dorés et ambres. Les ébénistes d'Essaouira travaillent ce bois précieux à la main pour créer coffrets, échiquier, instruments et sculptures incrustés de nacre et de citronnier.`,
            },
            {
                id: 'argane',
                name: 'Huile d\'Argan',
                sub: 'Or liquide du Maroc',
                localImage: '/assets/artisanat/argan.jpg',
                unsplashQuery: 'argan oil Morocco organic Essaouira traditional',
                description: `L'arganier (Argania spinosa), arbre sacré des Berbères, ne pousse qu'au Maroc dans une zone biosphère de 800 000 hectares. Les femmes des coopératives soussies extraient à la main l'huile des amandes d'argane selon des gestes transmis depuis des millénaires. Cette huile d'or, riche en vitamine E et en acides gras insaturés, est utilisée en cuisine et en cosmétique.`,
            },
            {
                id: 'instruments',
                name: 'Instruments Gnawa',
                sub: 'Crotales & guembri',
                localImage: '/assets/artisanat/gnaoua.jpg',
                unsplashQuery: 'Gnawa music instruments Morocco guembri',
                description: `La musique Gnawa, inscrite au patrimoine immatériel de l'UNESCO en 2019, est arrivée au Maroc avec les esclaves sub-sahariens aux XVIe-XVIIe siècles. Les artisans d'Essaouira fabriquent à la main le guembri — luth à corde grave aux sons hypnotiques — et les qraqabs — crotales métalliques dont le claquement rythmique guide les cérémonies de guérison lilas.`,
            },
        ],
        meknes: [
            {
                id: 'architecture_meknes',
                name: 'Architecture Colossale',
                sub: 'Génie Ismaïlien',
                unsplashQuery: 'Meknes ramparts walls imperial Morocco',
                description: `L'architecture ismaïlienne de Meknès se distingue par ses proportions colossales. Les murailles atteignent 40km de longueur et 5m d'épaisseur. Moulay Ismaïl employa 50 000 esclaves et prisonniers pour édifier sa capitale en moins de 25 ans.`,
            },
            {
                id: 'broderie_meknes',
                name: 'Broderie de Meknès',
                sub: 'Soie géométrique',
                unsplashQuery: 'Moroccan embroidery Meknes silk geometric',
                description: `La broderie meknessia se distingue par ses points comptés sur toile de lin, avec des motifs géométriques en fils de soie polychrome. Chaque pièce peut nécessiter plusieurs mois de travail.`,
            },
            {
                id: 'poterie_meknes',
                name: 'Poterie & Céramique',
                sub: 'Tradition millénaire',
                unsplashQuery: 'Meknes pottery ceramic Morocco traditional',
                description: `Les potiers de Meknès perpétuent une tradition millénaire avec des glazures caractéristiques en brun manganèse et vert cuivre sur fond crème.`,
            },
            {
                id: 'systeme_meknes',
                name: 'Khettaras & Greniers',
                sub: 'Maîtrise de l\'eau',
                unsplashQuery: 'Heri Souani granary Meknes underground',
                description: `Les Heri es-Souani, greniers royaux de Moulay Ismaïl, pouvaient stocker des provisions pour 12 000 chevaux. Leur système de ventilation souterrain maintient une température constante de 15°C.`,
            },
            {
                id: 'jmaa_meknes',
                name: 'Garde Noire Ismaïlienne',
                sub: 'Organisation militaire',
                unsplashQuery: 'Meknes imperial guard Morocco Moulay Ismail',
                description: `Moulay Ismaïl instaura un système de gouvernance militaire unique avec sa garde noire — les Abids — corps d'élite de 150 000 soldats protégeant l'empire.`,
            }
        ],
        tanger: [
            {
                id: 'architecture_tanger',
                name: 'Architecture',
                sub: 'Dialogue Stylistique',
                unsplashQuery: 'Tangier architecture Kasbah white blue walls',
                description: `L'architecture tangéroise est un dialogue entre les styles arabo-andalous de la Kasbah et les façades Art Déco de la Ville Nouvelle. Un métissage architectural unique, reflétant son statut d'ancienne ville internationale.`,
            },
            {
                id: 'tissage_rif',
                name: 'Tissage du Rif (Mendil)',
                sub: 'Textile de coton rayé',
                unsplashQuery: 'Moroccan Rif weaving textile red white stripes',
                description: `Le Mendil est un tissu de coton à rayures rouges et blanches, porté par les femmes du Rif, symbole de l'identité régionale du Nord. Il est tissé à la main sur d'étroits métiers traditionnels en bois.`,
            },
            {
                id: 'maroquinerie_nord',
                name: 'Maroquinerie du Nord',
                sub: 'Cuirs souples',
                unsplashQuery: 'Moroccan leather craft Tangier bags',
                description: `Héritière d'un savoir-faire ancien, la maroquinerie de Tanger se distingue par la souplesse de ses cuirs et ses finitions raffinées, souvent ornées de motifs andalous discrètement incisés dans la peau tannée.`,
            }
        ],
    },

    // ── Gastronomie ─────────────────────────────────────────────────
    gastronomie: {
        marrakech: [
            {
                id: 'tanjia',
                nom: 'Tanjia Marrakchia',
                localImage: '/assets/food/tanjia.png',
                unsplashQuery: 'Tanjia Marrakech clay pot hammam ashes',
                description: 'Le plat emblématique des artisans. Cuite pendant des heures dans un pot en terre sous les cendres du four du hammam, elle symbolise l\'ingéniosité urbaine de la ville rouge.',
            },
            {
                id: 'mechoui',
                nom: 'Méchoui',
                localImage: '/assets/food/mechoui.png',
                unsplashQuery: 'Mechoui whole roasted lamb Morocco',
                description: 'Agneau entier rôti dans des fours en terre verticaux. Plat des grandes célébrations, témoignant de l\'hospitalité légendaire de Marrakech.',
            },
            {
                id: 'harira_marrakech',
                nom: 'Harira Marrakchia',
                localImage: '/assets/food/harira.png',
                unsplashQuery: 'Harira soup Morocco spiced tomato',
                description: 'Soupe dense et parfumée, plus épicée qu\'ailleurs, qui marque la fin de la journée et le rassemblement social sur la place Jemaa el-Fna.',
            },
        ],
        fes: [
            {
                id: 'pastilla',
                nom: 'Pastilla au Pigeon',
                localImage: '/assets/food/pastilla.png',
                unsplashQuery: 'Pastilla pigeon Moroccan ouarqa pastry Fes',
                description: 'Le sommet de l\'art culinaire fassi. Mélange complexe de sucré-salé protégé par des feuilles de ouarqa ultra-fines. Héritage direct de l\'Andalousie.',
            },
            {
                id: 'khlii',
                nom: 'Khlii',
                localImage: '/assets/food/khlii.png',
                unsplashQuery: 'Khlii dried preserved meat Morocco breakfast',
                description: 'Viande séchée et confite dans la graisse. Inventé pour conserver la viande durant les longs voyages, incontournable du petit-déjeuner fassi.',
            },
            {
                id: 'couscous_fassi',
                nom: 'Couscous aux Sept Légumes Fassi',
                localImage: '/assets/food/couscous_fassi.png',
                unsplashQuery: 'Moroccan couscous seven vegetables saffron Fes',
                description: 'Réputé pour sa finesse, il se distingue par l\'équilibre parfait de ses épices — safran et gingembre — et la qualité du grain roulé à la main.',
            },
        ],
        chefchaouen: [
            {
                id: 'bissara',
                nom: 'Bissara',
                localImage: '/assets/food/bissara.png',
                unsplashQuery: 'Bissara fava bean puree olive oil cumin Morocco',
                description: 'Purée de fèves ou pois cassés généreusement arrosée d\'huile d\'olive locale et saupoudrée de cumin. L\'énergie pure des montagnards du Rif.',
            },
            {
                id: 'jben',
                nom: 'Jben — Fromage de Chèvre',
                localImage: '/assets/food/jben.png',
                unsplashQuery: 'Jben fresh goat cheese Morocco palm leaves Rif',
                description: 'Fabriqué artisanalement dans les montagnes du Rif, servi frais dans des feuilles de palmier. Symbole de la pureté des produits du terroir.',
            },
            {
                id: 'tagine_chevre',
                nom: 'Tagine de Chèvre aux Pruneaux',
                localImage: '/assets/food/tagine_chevre.png',
                unsplashQuery: 'goat tagine prunes dried fruit Morocco mountain',
                description: 'La viande de chèvre typique de la région, mariée à la douceur des fruits secs. Illustre la richesse des saveurs de la montagne.',
            },
        ],
        essaouira: [
            {
                id: 'sardines',
                nom: 'Sardines Grillées du Port',
                localImage: '/assets/food/sardines.png',
                unsplashQuery: 'grilled sardines charcoal port Essaouira Morocco',
                description: 'Fraîchement pêchées et grillées au port sur charbon de bois. L\'essence même d\'Essaouira : simplicité, océan et convivialité.',
            },
            {
                id: 'tagine_lotte',
                nom: 'Tagine de Lotte aux Légumes',
                localImage: '/assets/food/tagine_lotte.png',
                unsplashQuery: 'monkfish tagine vegetables Atlantic Morocco',
                description: 'La lotte, poisson noble de l\'Atlantique, cuisinée avec des épices douces. Témoigne du lien indéfectible entre Essaouira et la mer.',
            },
            {
                id: 'couscous_poisson',
                nom: 'Couscous au Poisson',
                localImage: '/assets/food/couscous_poisson.png',
                unsplashQuery: 'Moroccan fish couscous coastal Essaouira seafood',
                description: 'Variante rare et raffinée propre aux villes côtières. Le poisson remplace la viande pour une légèreté typiquement souirie.',
            },
        ],
        meknes: [
            {
                id: 'kefta_chameau',
                nom: 'Kefta de Chameau Meknassia',
                localImage: '/assets/food/kefta_chameau.png',
                unsplashQuery: 'camel kefta grilled meat sandwich Morocco medina',
                description: `Spécialité emblématique de la médina de Meknès. La viande de chameau, réputée pour sa tendreté et son goût unique, est préparée en kefta grillée et servie dans des sandwiches généreux avec herbes fraîches et harissa maison.`,
            },
            {
                id: 'tajine_lapin',
                nom: 'Tajine de Lapin aux Olives',
                localImage: '/assets/food/tajine_lapin.png',
                unsplashQuery: 'rabbit tagine green olives preserved lemon Morocco',
                description: `Meknès, capitale de l'olivier, met à l'honneur ses célèbres olives vertes dans ce plat raffiné. Le lapin est mijoté lentement avec citron confit et huile d'olive de première pression à froid.`,
            },
            {
                id: 'mhammar',
                nom: 'Mhammar Meknassi',
                localImage: '/assets/food/mhammar.png',
                unsplashQuery: 'Moroccan mhammar roasted chicken saffron almonds',
                description: `Plat de fête des cités impériales. Agneau ou poulet rôti jusqu'au fondant, nappé d'une sauce onctueuse au safran et gingembre, garni d'amandes grillées dorées. La quintessence de la table royale ismaïlienne.`,
            }
        ],
        tanger: [
            {
                id: 'tagine_poisson_tgr',
                nom: 'Tagine de Poisson',
                localImage: '/assets/food/tagine_poisson_tanger.jpg',
                unsplashQuery: 'Fish tagine Tangier style Mediterranean',
                description: `La spécialité marine préparée avec du poisson frais du détroit et une chermoula riche en ail, citron vert et d'olives juteuses, servis en équilibre entre mer et terre.`,
            },
            {
                id: 'the_menthe_tgr',
                nom: 'Thé à la Menthe du Nord',
                localImage: '/assets/food/the_menthe_tanger.jpg',
                unsplashQuery: 'Moroccan mint tea pine nuts Tangier',
                description: `À Tanger, le thé est servi avec une menthe sauvage parfumée et parfois accompagné de pignons de pin, reflétant les influences andalouses de la région et du port.`,
            },
            {
                id: 'bissara_tgr',
                nom: 'Bissara du Nord',
                localImage: '/assets/food/bissara_tanger.jpg',
                unsplashQuery: 'Bissara fava bean pure soup Morocco Tangier',
                description: `Purée de fèves onctueuse avec huile d'olive du Rif et cumin, typique des matins tangérois pour faire le plein d'énergie face à la brise marine.`,
            }
        ],
    },

    // ── Gastro subtitles per city ────────────────────────────────────
    gastroSubtitles: {
        marrakech: 'La Cuisine de la Rue et du Partage',
        fes: 'Le Raffinement de la Table Impériale',
        chefchaouen: 'La Diète Méditerranéenne du Rif',
        essaouira: 'La Fraîcheur de l\'Atlantique',
        meknes: 'L\'Opulence de la Table Ismaïlienne',
        tanger: 'Le Goût des Deux Mers',
    },

    getGastronomie(cityId) {
        return this.gastronomie[cityId] || [];
    },

    // ── Hero panoramic queries for Home ─────────────────────────────
    heroPanoramas: [
        {
            unsplashQuery: 'Morocco medina ancient city',
            label: 'À la découverte',
            title: 'Jemaa el-Fna',
            sub: 'La place qui ne dort jamais',
            cityId: 'marrakech',
        },
        {
            unsplashQuery: 'Fes tannery medina Morocco',
            label: 'Patrimoine mondial',
            title: 'Médina de Fès',
            sub: 'Labyrinthe de mémoire',
            cityId: 'fes',
        },
        {
            unsplashQuery: 'Essaouira ramparts ocean Morocco',
            label: 'Face à l\'Atlantique',
            title: 'Remparts d\'Essaouira',
            sub: 'La cité des vents',
            cityId: 'essaouira',
        },
    ],

    // ── State ────────────────────────────────────────────────────────
    favorites: new Set(JSON.parse(localStorage.getItem('atlas_favorites') || '[]')),

    toggleFavorite(monumentId) {
        if (this.favorites.has(monumentId)) {
            this.favorites.delete(monumentId);
        } else {
            this.favorites.add(monumentId);
        }
        localStorage.setItem('atlas_favorites', JSON.stringify([...this.favorites]));
        return this.favorites.has(monumentId);
    },

    isFavorite(monumentId) {
        return this.favorites.has(monumentId);
    },

    getCity(cityId) {
        return this.cities.find(c => c.id === cityId);
    },

    getMonument(monumentId) {
        return this.monuments.find(m => m.id === monumentId);
    },

    getMonumentsByCity(cityId) {
        return this.monuments.filter(m => m.cityId === cityId);
    },

    getFavoriteMonuments() {
        return this.monuments.filter(m => this.favorites.has(m.id));
    },
};
